/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 放送局一覧
         * @description ユーザーがチューナー設定で有効化した放送局の一覧を返す。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 放送局の配列 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelList"];
                    };
                };
                /** @description 内部エラー */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 番組表
         * @description 指定された「放送日 (JST 05:00 境界)」の番組を時刻順で返す。放送日 = 日本の番組表慣習 (翌日 05:00 までを同じ日付として扱う、例: 4/19 25時=4/20 01:00 JST)。 date 未指定時は現在の放送日、all=1 で全期間。
         */
        get: {
            parameters: {
                query?: {
                    date?: string;
                    all?: "0" | "1";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 番組の配列 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProgramList"];
                    };
                };
                /** @description 内部エラー */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 番組1件
         * @description プログラム ID で1件返す。TVDB 紐付け済みなら tvdb フィールドが付く。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 番組 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Program"];
                    };
                };
                /** @description 見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{id}/tvdb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * TVDB 手動マッチ
         * @description 番組を指定 TVDB エントリへ手動で紐付ける。同じ正規化タイトルを持つ番組すべてに波及し、title_overrides に user_set=true で記録される (以降 auto matcher は上書きしない)。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @example 188501 */
                        tvdbId: number;
                    };
                };
            };
            responses: {
                /** @description 確定した TVDB エントリ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TvdbEntry"];
                    };
                };
                /** @description 不正な TVDB id */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 番組が見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        /**
         * TVDB マッチ解除
         * @description 番組の TVDB 紐付けを解除する。同じ正規化タイトルの全番組で解除され、title_overrides に tvdbId=null, user_set=true で記録 (auto matcher は以降再紐付けしない)。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 解除完了 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 番組が見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{id}/tvdb-episode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * TVDB 話数 手動設定
         * @description 番組の TVDB シーズン/話数を手動で設定する。自動マッチャーが誤った S/E を割り当てた再放送などに対する per-airing の修正で、同タイトル他番組には波及しない。season/episode のいずれかが null の場合は S/E/名前をクリアする。
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @example 2 */
                        season: number | null;
                        /** @example 14 */
                        episode: number | null;
                    };
                };
            };
            responses: {
                /** @description 更新後の番組 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Program"];
                    };
                };
                /** @description 番組が見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 録画一覧
         * @description 全 recording 行を返す。?state= でフィルタ可能 (カンマ区切りで複数)。
         */
        get: {
            parameters: {
                query?: {
                    state?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description recording 配列 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecordingList"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 録画作成 (予約)
         * @description チューナー競合 (409 tuner-full) または既存重複 (409 duplicate) の場合はエラーを返す。 force: true で上書き可能。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateRecording"];
                };
            };
            responses: {
                /** @description recording 作成 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Recording"];
                    };
                };
                /** @description 番組が見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 競合または重複 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 録画詳細 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description recording */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Recording"];
                    };
                };
                /** @description 見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * recording 削除 / キャンセル
         * @description 状態に応じて: scheduled=キャンセル, recording=abort, ready/failed=ファイル削除。 いずれも DB 行を削除する。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * recording の設定更新
         * @description state=scheduled の recording のみ編集可能。priority/quality/keepRaw/marginPre/marginPost を 部分更新する。margin が変わると pg-boss の RECORD_START/RECORD_STOP を再スケジュールする。
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateRecording"];
                };
            };
            responses: {
                /** @description 更新後 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Recording"];
                    };
                };
                /** @description 見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 編集不可 (scheduled 以外) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/recordings/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 録画を即時停止
         * @description state=recording のときのみ有効。アクティブな録画パイプを即座に閉じて .part を本ファイルへ rename し、state を encoding または ready に更新する。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 停止成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description recording が見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 録画中でない */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{id}/drops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * TS ドロップ統計
         * @description 録画完了時に記録された TS continuity-counter ベースのドロップ／エラー／スクランブル集計を返す。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ドロップ統計 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecordingDropLog"];
                    };
                };
                /** @description 見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{id}/encode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 再エンコードを投入
         * @description 指定 preset (省略時は ENCODE_DEFAULT_PRESET) で ffmpeg エンコードを pg-boss のジョブとして投入する。 ready / failed の recording に対して使う。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RecordingEncodeRequest"];
                };
            };
            responses: {
                /** @description キュー投入済み */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecordingEncodeAccepted"];
                    };
                };
                /** @description preset 未知 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 録画ルール一覧 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ルール配列 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuleList"];
                    };
                };
            };
        };
        put?: never;
        /**
         * ルール作成
         * @description 同じ TVDB id に対する series ルールはすでに存在する場合 409 を返す。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateRule"];
                };
            };
            responses: {
                /** @description ルール作成 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Rule"];
                    };
                };
                /** @description 重複 (同 TVDB の series rule が既存) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/expand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ルールを即時展開 (非推奨)
         * @deprecated
         * @description 非推奨。副作用を伴う操作には POST /admin/expand-rules を使用してください。GET のまま残してあるのは既存ジョブ/ブックマークとの互換のため。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 展開サマリ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuleExpandSummary"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** ルール削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | null;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** ルール更新 (有効化/無効化・属性変更) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | null;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateRule"];
                };
            };
            responses: {
                /** @description 更新後のルール */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Rule"];
                    };
                };
                /** @description 見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/tvdb/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * TVDB 検索
         * @description シリーズ/映画をタイトルで検索。キーワード未指定時は全件返す (fixture 動作)。
         */
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ヒット一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TvdbList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tvdb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * TVDB カタログ (series キーでマップ)
         * @description Program.series と一致するキーで TvdbEntry が得られる。Fixture 提供者の実装上、登録済みの紐付けのみ返る。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description カタログ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TvdbCatalog"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tvdb/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** TVDB 詳細 (ID指定) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | null;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description エントリ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TvdbEntry"];
                    };
                };
                /** @description 見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tvdb/{id}/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * TVDB シリーズのエピソード一覧
         * @description tvdb_entries.episodes にキャッシュされた aired-order エピソード配列を返す。UI の「話数選択」プルダウン向け。キャッシュ未ヒット時は空配列。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | null;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description エピソード一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TvdbEpisodeList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** チューナー稼働状況 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description チューナー配列 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TunerList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/now-recording": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 現在録画中の番組 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 録画中配列 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NowRecordingList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuners/allocation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 物理チューナーごとの予約割当
         * @description 優先度ベースのアロケータが配置した、物理チューナーごとの予約チェーンを返す。UI のデバッグ/表示用。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description チューナー割当スナップショット */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TunerAllocation"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** システムステータス (ストレージ・予約件数・バージョン) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ステータス */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SystemStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 予約ランキング (JCOM由来)
         * @description JCOM TV ガイドの予約ランキングをキャッシュして返す。 `genre` 未指定時は `all` (総合)。3時間ごとに裏でバックグラウンド同期される。
         */
        get: {
            parameters: {
                query?: {
                    genre?: components["schemas"]["RankingGenre"] & unknown;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ランキング (順位昇順) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RankingList"];
                    };
                };
                /** @description 内部エラー */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/refresh-epg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * EPG を今すぐ更新
         * @description 通常は pg-boss が 10 分ごとに実行している scheduleService.refresh() + matchService.enrichUnmatched() をその場で同期実行する。完了まで返らないので大規模な番組表取得では数秒〜数十秒かかりうる。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 更新結果 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminRefreshEpgResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/expand-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ルールを今すぐ展開
         * @description 全ての有効なルールに対して ruleExpander を即時実行し、マッチする未予約の番組を予約化する。既存の GET /rules/expand と同じ動作だが、副作用のある操作は POST が正式。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 展開サマリ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminExpandRulesResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/recorded-history/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 録画履歴を recordings テーブルから再構築
         * @description recordings テーブルの ready/failed 行から recorded_history 行を生成する。既存の tvdb tuple ユニーク制約で重複行は自動的にスキップされる。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 挿入件数 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminRebuildHistoryResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/recorded-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 録画履歴を一覧 */
        get: {
            parameters: {
                query?: {
                    tvdbId?: number | null;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 履歴行 (createdAt 降順) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecordedHistory"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/capacity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ディスク容量と sweep 閾値を取得
         * @description RECORDING_DIR を含むファイルシステムを statfs(2) で調べ、合計・使用・空き容量と disk.sweep が発動する閾値を返す。閾値は env DISK_SWEEP_MIN_FREE_GB が優先、未設定なら total の 5%。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ディスク容量サマリ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DiskStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/capacity/sweep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ディスク sweep を今すぐ実行
         * @description 通常 pg-boss が 1 時間ごとに実行している capacityService.sweep() を同期的に走らせる。保護 (protected=true) されていない state=ready/failed の行を古い順に削除し、空き容量が 閾値を上回ったら停止する。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["DiskSweepBody"];
                };
            };
            responses: {
                /** @description 削除結果 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DiskSweepResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/epg-live/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * EIT live poll を今すぐ実行
         * @description 通常 pg-boss が 1 分ごとに走らせている epgLiveService.pollOnce() を同期実行する。MIRAKURUN_URL が設定されていれば Mirakurun /api/programs を再取得して diff、未設定なら programs テーブルと reserves.endAt の差分だけ同期する。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EpgLivePollBody"];
                };
            };
            responses: {
                /** @description poll 結果 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EpgLivePollResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/channel-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * チャンネルソース一覧
         * @description 登録済みの m3u / Mirakurun アップストリームを取得する。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 登録済みソース (新しい順) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelSourceList"];
                    };
                };
            };
        };
        put?: never;
        /** チャンネルソースを追加 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateChannelSource"];
                };
            };
            responses: {
                /** @description 追加した行 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelSource"];
                    };
                };
                /** @description 入力エラー */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/channel-sources/{id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** チャンネルソースを今すぐ同期 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | null;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description sync 結果 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelSourceSyncResult"];
                    };
                };
                /** @description 存在しない id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/channel-sources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** チャンネルソースを削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | null;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除完了 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 存在しない id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/gpu/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ffmpeg で GPU エンコーダを検出
         * @description NVENC / VAAPI / QSV / VideoToolbox の 8 encoder に対し 0.5 秒の null encode を並列実行し、どの encoder が使えるか返す。結果は system_settings.gpu.lastProbe にキャッシュされる。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description probe 結果 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GpuProbeResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/gpu/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 現在の GPU 設定と直近 probe 結果
         * @description `enabled` / `preferred` / `lastProbe` を返す。UI の Settings 画面は初期表示でこれを読み、必要になったタイミングで `/admin/gpu/probe` を叩く。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description GPU ステータス */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GpuStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/gpu/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * GPU エンコード設定を更新
         * @description enabled/preferred を部分更新する。送らなかった key は変更しない。 preferred を null にすると resolvePreset は CPU プリセットにフォールバックする。
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GpuSettingsPatch"];
                };
            };
            responses: {
                /** @description 更新後のステータス */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GpuStatus"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 受信形態
         * @enum {string}
         */
        BcType: "GR" | "BS" | "CS";
        Channel: {
            /** @example nhk-g */
            id: string;
            /** @example NHK総合 */
            name: string;
            /** @example NHK G */
            short: string;
            /**
             * @description リモコン番号等の表示用番号
             * @example 011
             */
            number: string;
            type: components["schemas"]["BcType"];
            /**
             * @description UI 上の識別色 (CSS color)
             * @example oklch(0.55 0.12 28)
             */
            color: string;
        };
        ChannelList: components["schemas"]["Channel"][];
        Error: {
            /** @example reserve.conflict */
            code: string;
            /** @example 予約時間帯に空きチューナーがありません */
            message: string;
            detail?: {
                [key: string]: unknown;
            };
        };
        Genre: {
            /** @example drama */
            key: string;
            /** @example ドラマ */
            label: string;
            /**
             * @description UI 表示色
             * @example oklch(0.62 0.12 20)
             */
            dot: string;
        };
        TvdbSeries: {
            /** @example 389042 */
            id: number;
            /** @example kaze-no-gunzo */
            slug: string;
            /** @example 風の群像 */
            title: string;
            /** @example Kaze no Gunzō */
            titleEn: string;
            network: string;
            year: number;
            /** @description ポスター画像識別子 (URL or internal key) */
            poster: string;
            matchedBy: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "series";
            totalSeasons: number;
            currentSeason: number;
            currentEp: number;
            totalEps: number;
            /** @enum {string} */
            status: "continuing" | "ended";
        };
        TvdbMovie: {
            /** @example 389042 */
            id: number;
            /** @example kaze-no-gunzo */
            slug: string;
            /** @example 風の群像 */
            title: string;
            /** @example Kaze no Gunzō */
            titleEn: string;
            network: string;
            year: number;
            /** @description ポスター画像識別子 (URL or internal key) */
            poster: string;
            matchedBy: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "movie";
            /** @description 本編時間(分) */
            runtime: number;
            director: string;
            /** @example 9.3 */
            rating: number;
        };
        TvdbEntry: components["schemas"]["TvdbSeries"] | components["schemas"]["TvdbMovie"];
        Program: {
            /** @example nhk-g_2026-04-19T20:00 */
            id: string;
            /** @example nhk-g */
            ch: string;
            /**
             * Format: date-time
             * @example 2026-04-19T20:00:00+09:00
             */
            startAt: string;
            /**
             * Format: date-time
             * @example 2026-04-19T20:45:00+09:00
             */
            endAt: string;
            /** @example 大河ドラマ「風の群像」第16回 */
            title: string;
            genre: components["schemas"]["Genre"];
            /** @example #16 */
            ep: string | null;
            /** @example taiga-2026 */
            series: string | null;
            hd?: boolean;
            desc?: string;
            /**
             * @example {
             *       "出演者": "主演:…",
             *       "スタッフ": "脚本:…"
             *     }
             */
            extended?: {
                [key: string]: string;
            };
            /** @example 1080i */
            video?: string;
            tvdb?: components["schemas"]["TvdbEntry"];
            tvdbSeason?: number | null;
            tvdbEpisode?: number | null;
            tvdbEpisodeName?: string | null;
        };
        ProgramList: components["schemas"]["Program"][];
        /** @enum {string} */
        Priority: "high" | "medium" | "low";
        /** @enum {string} */
        Quality: "1080i" | "720p";
        RecordingSource: {
            /** @enum {string} */
            kind: "once";
        } | {
            /** @enum {string} */
            kind: "rule";
            ruleId: number;
        } | {
            /** @enum {string} */
            kind: "series";
            tvdbId: number;
        };
        /** @enum {string} */
        RecordingState: "scheduled" | "recording" | "encoding" | "ready" | "failed" | "conflict";
        RecordingDropSummary: {
            errorCnt: number;
            dropCnt: number;
            scramblingCnt: number;
        };
        Recording: {
            /** @example rec_01HX... */
            id: string;
            /** @example nhk-g_2026-04-19T20:00 */
            programId: string;
            ch: string;
            title: string;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            priority: components["schemas"]["Priority"];
            quality: components["schemas"]["Quality"];
            /** @description TS (raw) を保持するか */
            keepRaw: boolean;
            /**
             * @description 開始前マージン(秒)
             * @example 0
             */
            marginPre: number;
            /**
             * @description 終了後マージン(秒)
             * @example 30
             */
            marginPost: number;
            source: components["schemas"]["RecordingSource"];
            state: components["schemas"]["RecordingState"];
            allocatedTunerIdx?: number;
            /** Format: date-time */
            recordedAt?: string | null;
            filename?: string | null;
            /** @description ファイルサイズ(GB) */
            size?: number | null;
            /** @description 録画時間(分) */
            duration?: number | null;
            encodeProgress?: number;
            encodePreset?: string | null;
            encodeError?: string | null;
            thumb?: string | null;
            /** @description ffmpeg サムネが生成済みなら true。false の場合 thumb は TVDB ポスター等のフォールバック。 */
            thumbGenerated?: boolean;
            /** @description true の行は自動ディスク sweep の対象外。 */
            protected?: boolean;
            new?: boolean;
            tvdbId?: number | null;
            series?: string | null;
            season?: number | null;
            ep?: number | null;
            epTitle?: string | null;
            ruleMatched?: string | null;
            /** Format: date-time */
            originalStartAt?: string | null;
            /** Format: date-time */
            originalEndAt?: string | null;
            extendedBySec?: number;
            drops?: components["schemas"]["RecordingDropSummary"];
        };
        RecordingList: components["schemas"]["Recording"][];
        CreateRecording: {
            programId: string;
            priority?: components["schemas"]["Priority"] & unknown;
            quality?: components["schemas"]["Quality"] & unknown;
            /** @default false */
            keepRaw: boolean;
            /** @default 0 */
            marginPre: number;
            /** @default 30 */
            marginPost: number;
            source?: components["schemas"]["RecordingSource"] & unknown;
            /** @default false */
            force: boolean;
        };
        UpdateRecording: {
            priority?: components["schemas"]["Priority"];
            quality?: components["schemas"]["Quality"];
            keepRaw?: boolean;
            marginPre?: number;
            marginPost?: number;
        };
        RecordingDropPerPid: {
            [key: string]: {
                err: number;
                drop: number;
                scr: number;
            };
        };
        RecordingDropLog: {
            recordingId: string;
            errorCnt: number;
            dropCnt: number;
            scramblingCnt: number;
            perPid: components["schemas"]["RecordingDropPerPid"];
            /** Format: date-time */
            createdAt: string;
        };
        RecordingEncodeAccepted: {
            recordingId: string;
            preset: string;
            /** @enum {boolean} */
            queued: true;
        };
        RecordingEncodeRequest: {
            /** @enum {string} */
            preset?: "h265-1080p" | "h264-720p" | "audio-only" | "h265-1080p-nvenc" | "h264-720p-nvenc" | "h265-1080p-vaapi" | "h264-720p-vaapi" | "h265-1080p-qsv" | "h264-720p-qsv";
        };
        RuleNextMatch: {
            ch: string;
            title: string;
            /** Format: date-time */
            at: string;
        } | null;
        /** @enum {string} */
        RuleKind: "keyword" | "series";
        TimeRangeDeny: {
            /** @example 02:00 */
            start: string;
            /** @example 05:00 */
            end: string;
        };
        Rule: {
            /** @example 1 */
            id: number;
            /** @example 大河ドラマ 風の群像 */
            name: string;
            keyword: string;
            /** @description 対象チャンネル id */
            channels: string[];
            enabled: boolean;
            /** @description これまでの一致件数 (累計) */
            matches: number;
            nextMatch: components["schemas"]["RuleNextMatch"];
            priority: components["schemas"]["Priority"];
            quality: components["schemas"]["Quality"];
            skipReruns: boolean;
            kind: components["schemas"]["RuleKind"];
            tvdb?: components["schemas"]["TvdbEntry"];
            /**
             * @description タイトルにこれらのキーワードが含まれる番組は除外 (傑作選・総集編など)
             * @default []
             * @example [
             *       "傑作選",
             *       "総集編"
             *     ]
             */
            ngKeywords: string[];
            /**
             * @description 番組ジャンル key (news/info/…) がここに含まれる番組は除外
             * @default []
             * @example [
             *       "news"
             *     ]
             */
            genreDeny: string[];
            /**
             * @description 開始時刻 (JST) がいずれかのレンジ内に入る番組は除外
             * @default []
             */
            timeRangeDeny: components["schemas"]["TimeRangeDeny"][];
        };
        RuleList: components["schemas"]["Rule"][];
        RuleExpandSummary: {
            matchedPrograms: number;
            createdRecordings: number;
            conflicts: {
                duplicate: number;
                tunerFull: number;
            };
        };
        CreateRule: {
            name: string;
            keyword: string;
            /** @description 対象チャンネル id */
            channels?: string[];
            enabled?: boolean;
            priority?: components["schemas"]["Priority"];
            quality?: components["schemas"]["Quality"];
            skipReruns?: boolean;
            kind?: components["schemas"]["RuleKind"];
            tvdb?: components["schemas"]["TvdbEntry"];
            /**
             * @description タイトルにこれらのキーワードが含まれる番組は除外 (傑作選・総集編など)
             * @default []
             * @example [
             *       "傑作選",
             *       "総集編"
             *     ]
             */
            ngKeywords: string[];
            /**
             * @description 番組ジャンル key (news/info/…) がここに含まれる番組は除外
             * @default []
             * @example [
             *       "news"
             *     ]
             */
            genreDeny: string[];
            /**
             * @description 開始時刻 (JST) がいずれかのレンジ内に入る番組は除外
             * @default []
             */
            timeRangeDeny: components["schemas"]["TimeRangeDeny"][];
        };
        UpdateRule: {
            name?: string;
            keyword?: string;
            /** @description 対象チャンネル id */
            channels?: string[];
            enabled?: boolean;
            priority?: components["schemas"]["Priority"];
            quality?: components["schemas"]["Quality"];
            skipReruns?: boolean;
            kind?: components["schemas"]["RuleKind"];
            tvdb?: components["schemas"]["TvdbEntry"];
            /**
             * @description タイトルにこれらのキーワードが含まれる番組は除外 (傑作選・総集編など)
             * @default []
             * @example [
             *       "傑作選",
             *       "総集編"
             *     ]
             */
            ngKeywords: string[];
            /**
             * @description 番組ジャンル key (news/info/…) がここに含まれる番組は除外
             * @default []
             * @example [
             *       "news"
             *     ]
             */
            genreDeny: string[];
            /**
             * @description 開始時刻 (JST) がいずれかのレンジ内に入る番組は除外
             * @default []
             */
            timeRangeDeny: components["schemas"]["TimeRangeDeny"][];
        };
        TvdbList: components["schemas"]["TvdbEntry"][];
        /** @description Program.series キー → TvdbEntry のマップ。UI 側の「この番組のTVDB紐付け」参照で使う。 */
        TvdbCatalog: {
            [key: string]: components["schemas"]["TvdbEntry"];
        };
        TvdbEpisode: {
            /** @example 2 */
            s: number;
            /** @example 14 */
            e: number;
            /** @example 2026-04-19 */
            aired?: string;
            /** @example それぞれの春 */
            name?: string;
        };
        TvdbEpisodeList: components["schemas"]["TvdbEpisode"][];
        TunerState: {
            type: components["schemas"]["BcType"];
            total: number;
            inUse: number;
        };
        TunerList: components["schemas"]["TunerState"][];
        NowRecording: {
            id: string;
            title: string;
            ch: string;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            progress: number;
            series: string | null;
            tvdbId: number | null;
        };
        NowRecordingList: components["schemas"]["NowRecording"][];
        TunerSlotRecording: {
            id: string;
            ch: string;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            priority: components["schemas"]["Priority"];
            title: string;
        };
        TunerSlot: {
            tunerIdx: number;
            types: ("GR" | "BS" | "CS" | "SKY")[];
            recordings: components["schemas"]["TunerSlotRecording"][];
        };
        TunerAllocation: {
            slots: components["schemas"]["TunerSlot"][];
        };
        StorageStatus: {
            totalBytes: number;
            usedBytes: number;
        };
        SystemStatus: {
            storage: components["schemas"]["StorageStatus"];
            /** @description 本日残り予約件数 */
            upcomingReserves: number;
            /**
             * @description 表示基準日 (YYYY-MM-DD)
             * @example 2026-04-19
             */
            today: string;
            version: string;
        };
        /**
         * @example all
         * @enum {string}
         */
        RankingGenre: "all" | "movie" | "drama" | "sport" | "anime" | "music" | "var" | "doc" | "edu";
        RankingItem: {
            /** @example 1 */
            rank: number;
            title: string;
            /** @description 次回放送局 — 放送予定が無いとき null */
            channelName: string | null;
            /** @description 前回順位との差 (正=上昇). 新規エントリは null */
            delta: number | null;
            /** @description 次回放送の番組名など。なければ null */
            quote: string | null;
            /** @description 次回放送番組の program id (svc-<serviceId>_<startAtIso>). JCOM 側で放送予定を解決できなかった場合は省略 */
            nextProgramId?: string;
            tvdb: Omit<components["schemas"]["TvdbEntry"], "type"> & (components["schemas"]["TvdbSeries"] | components["schemas"]["TvdbMovie"] | null);
            /**
             * Format: date-time
             * @description ISO-8601 UTC
             */
            syncedAt: string;
        };
        RankingList: {
            genre: components["schemas"]["RankingGenre"];
            items: components["schemas"]["RankingItem"][];
        };
        AdminRefreshEpgResult: {
            /** @description Mirakurun から取得して upsert した番組件数 */
            programsUpserted: number;
            /** @description TVDB 突き合わせで解決できた番組件数 */
            tvdbResolved: number;
            /** @description TVDB 突き合わせで解決できなかった番組件数 */
            tvdbMissed: number;
        };
        AdminExpandRulesResult: {
            matchedPrograms: number;
            createdRecordings: number;
            conflicts: {
                duplicate: number;
                tunerFull: number;
            };
        };
        AdminRebuildHistoryResult: {
            inserted: number;
        };
        RecordedHistory: {
            id: number;
            tvdbId: number | null;
            season: number | null;
            episode: number | null;
            normalizedTitle: string | null;
            /** Format: date-time */
            endAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        DiskStatus: {
            /** @description ファイルシステムの合計容量 */
            totalBytes: number;
            /** @description 使用中のバイト数 */
            usedBytes: number;
            /** @description 空き容量 */
            freeBytes: number;
            /** @description この値を下回ると sweep が走る閾値 (bytes) */
            threshold: number;
        };
        DiskSweepResult: {
            /** @description 削除した recordings.id の一覧 (古い順) */
            deletedIds: string[];
            /** @description 削除で解放した推定バイト数 (recordings.size * GiB) */
            freedBytes: number;
        };
        DiskSweepBody: {
            /** @description 閾値のワンショット上書き (bytes)。通常は env DISK_SWEEP_MIN_FREE_GB または総容量の 5% を使うが、強制 sweep や e2e テストで任意の閾値を指定したい場合に送る。 */
            minFreeBytes?: number;
        };
        EpgLivePollResult: {
            /** @description endAt がシフトして再スケジュールされた recording の id 一覧 */
            shifted: string[];
            /** @description 適用した diff アクション数 (bumpProgramRevision + updateEnd 合算) */
            touched: number;
        };
        EpgLivePollBody: {
            /**
             * @description 'auto' (省略時): MIRAKURUN_URL があれば Mirakurun fetch → diff、なければ programs-table fallback。 'programs-table': Mirakurun を無視し programs テーブルの endAt だけで reserves を同期する (テストで直接 DB を書き換えた場合などに使う)。
             * @enum {string}
             */
            source?: "auto" | "programs-table";
        };
        /**
         * @description チャンネルソース種別
         * @enum {string}
         */
        ChannelSourceKind: "m3u" | "mirakurun";
        ChannelSource: {
            /** @example 1 */
            id: number;
            /** @example IPTV JP */
            name: string;
            kind: components["schemas"]["ChannelSourceKind"];
            /**
             * Format: uri
             * @example https://example.com/iptv.m3u
             */
            url: string;
            /** @example true */
            enabled: boolean;
            /** Format: date-time */
            lastSyncAt: string | null;
            lastError: string | null;
            /** @description 前回の sync で登録できたチャンネル件数 */
            channelCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        ChannelSourceList: components["schemas"]["ChannelSource"][];
        CreateChannelSource: {
            /** @example IPTV JP */
            name: string;
            kind: components["schemas"]["ChannelSourceKind"];
            /**
             * Format: uri
             * @example https://example.com/iptv.m3u
             */
            url: string;
        };
        ChannelSourceSyncResult: {
            channelCount: number;
            error?: string;
        };
        /** @enum {string} */
        GpuEncoder: "h264_nvenc" | "hevc_nvenc" | "h264_vaapi" | "hevc_vaapi" | "h264_qsv" | "hevc_qsv" | "h264_videotoolbox" | "hevc_videotoolbox";
        GpuProbeDetail: {
            /** @description この encoder が 0.5s テスト encode に成功したか */
            ok: boolean;
            /** @description 失敗時の短い ffmpeg エラー (stderr 末尾 3 行まで) */
            error?: string;
        };
        GpuProbeResult: {
            /** @description ok=true だった encoder の一覧 (details から射影) */
            available: components["schemas"]["GpuEncoder"][];
            /** @description 8 encoder 全ての試行結果 (未検出でも key は必ず存在する) */
            details: {
                h264_nvenc?: components["schemas"]["GpuProbeDetail"];
                hevc_nvenc?: components["schemas"]["GpuProbeDetail"];
                h264_vaapi?: components["schemas"]["GpuProbeDetail"];
                hevc_vaapi?: components["schemas"]["GpuProbeDetail"];
                h264_qsv?: components["schemas"]["GpuProbeDetail"];
                hevc_qsv?: components["schemas"]["GpuProbeDetail"];
                h264_videotoolbox?: components["schemas"]["GpuProbeDetail"];
                hevc_videotoolbox?: components["schemas"]["GpuProbeDetail"];
            };
            /**
             * Format: date-time
             * @description probe を走らせた時刻 (ISO-8601)
             */
            probedAt: string;
        };
        GpuStatus: {
            /** @description 録画エンコード時に GPU プリセットへ自動昇格するか */
            enabled: boolean;
            preferred: components["schemas"]["GpuEncoder"] & (string | null);
            lastProbe: components["schemas"]["GpuProbeResult"] & (Record<string, never> | null);
        };
        GpuSettingsPatch: {
            enabled?: boolean;
            preferred?: components["schemas"]["GpuEncoder"] & (string | null);
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
